### ISSUE TITLE
ты конечно приколист )

### ISSUE THREAD

**Issue by ZevSuk** [Rocky-04/Movie_Rating_Migrator_Kinopoisk_to_IMDB#8]
я насчет проги [Movie_Rating_Migrator_Kinopoisk_to_IMDB]
работает глупо. открывается браузер, и только появляется страница с капчей чтобы хотябы галочку поставить - сразу зкрываетс. И так 3 раза. Я тупо не успеваю даже галочку поставить )). Подвердить что я не робот. А там еще и просит текст ввести яндекс проверочка. 
Ппц ты шустрый наверное, раз за те 3 секунды что браузер открыт, успеваеш все )
тайминг больше поставь. НА проверку робота секунд 20 точно надо

**Comment by Rocky-04** [comment]
На кинопоиске произошли изменения на странице капчи, поэтому работает некорректно.
Напишу когда исправлю.

**Comment by Rocky-04** [comment]
Программу обновил. Попробуй скачать заново и запусти еще раз

**Comment by StasNemy** [comment]
Всё ещё возникает данная ошибка. Открывается страница капчи, я успеваю нажать на проверку, происходит обработка капчей и прежде чем процесс завершается, страница закрывается.

Помимо всего прочего кажется не хватает доп описания.
Так например необходимо скачивать именно хром 108 версии, которую можно скачать здесь https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/1058982/
